### ISSUE TITLE
Solution for too much data - every two seconds?

### ISSUE THREAD

**Issue by hvorragend** [m-reuter/ha-addons#10]
Hello, unfortunately, I had to realize that the vzlogger-sensors update themselves far too frequently. The electricity meter sends its data every two seconds. This increases the load on the system and you can hardly create charts with this amount of data.

Do you know if you can change the timing for the MQTT transport? Neither "aggtime" nor "interval" helped me.

Many Thanks.

**Comment by m-reuter** [comment]
I am using:
aggtime: 10 
interval: 0
read_timeout: 10
and for the channels under each identifier you need to specify aggmode, e.g. avg or max depending on what you need.

**Comment by hvorragend** [comment]
I am using a push meter (Easymeter Q3B) and it pushes too much data. 

The aggtime doesn't help me.
I've tried several aggmodes (under each identifier). 

I think that this should be addressed to the vzlogger-project, isn't it?

**Comment by m-reuter** [comment]
Yes, you need to ask there, unless they have a way to address it via some settings, then we can add it here.
