### ISSUE TITLE
Missing License Information

### ISSUE THREAD

**Issue by seppelw** [m-reuter/ha-addons#3]
@m-reuter your repo does currently not feature a license. vzlogger is developed under GNU General Public License v3.0. What do you think about adding this to your project as well? I'm not sure whether or not HA does require some specific licensing for Addons. 

https://github.com/volkszaehler/vzlogger/blob/master/COPYING

**Comment by m-reuter** [comment]
Yes, we need a license. I do not like GNU. Will use MIT or BSD.
