### ISSUE TITLE
MQTT Connect error

### ISSUE THREAD

**Issue by dAjaY85** [m-reuter/ha-addons#4]
Hi @m-reuter,

when I am testing the new version, I get connection error of the MQTT, what can i do?

```
[Sep 10 18:50:40][mqtt] mosquitto_loop returned 4. trying reconnect
[Sep 10 18:50:41][mqtt] mosquitto_reconnect returned 14
[Sep 10 18:50:42][mqtt] mosquitto_loop returned 4. trying reconnect
[Sep 10 18:50:43][mqtt] mosquitto_reconnect returned 14
[Sep 10 18:50:44][mqtt] mosquitto_loop returned 4. trying reconnect
[Sep 10 18:50:45][mqtt] mosquitto_reconnect returned 14
[Sep 10 18:50:46][mqtt] mosquitto_loop returned 4. trying reconnect
```

**Comment by m-reuter** [comment]
Do you have the mosquito mqtt addon running? You need to set that up and enter the credentials also in the vzlogger2mqtt config.

**Comment by dAjaY85** [comment]
mosquito broker is running and i use the same username and passwort in vzlogger2mqtt.

Do you have an configuration example?

**Comment by m-reuter** [comment]
Double check also IP and port. You can also copy the vzlogger.config from the log output and try it standalone with your existing vzlogger.

**Comment by dAjaY85** [comment]
Now ist working, thank you
