### ISSUE TITLE
0.9.3 fails to start

### ISSUE THREAD

**Issue by buffcode** [m-reuter/ha-addons#9]
After updating to 0.9.3 the addon fails to start with

`s6-overlay-suexec: fatal: can only run as pid 1`

Obviously this has something to do with the latest changes to the base image and might be fixed in master already.

Can I some how update to master in HA or can you tag the master with a new version so we can update if it is fixed?

Thanks in advance!

**Comment by m-reuter** [comment]
this has been fixed already in   3b0a504feea2f  and 1cc83eaabee , probably just too slow to update the docker, as the build takes a while. Should all work now.

**Comment by m-reuter** [comment]
I will bump the . release versions again, so that it automatically updates for everyone who - in the meantime - installed 0.9.3

**Comment by buffcode** [comment]
I downgraded to 0.9.2 which also failed, then updated to 0.9.3 again which effectively updated to master and it works again. So updating to 0.9.4 should fix it for everyone!

❤️
